// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DXsIIZeRxKIpchmZMMRg9ZnKtxjijDU',
    appId: '1:217250091214:web:6127c988acbe96d779409f',
    messagingSenderId: '217250091214',
    projectId: 'true-teacher-dd0a3',
    authDomain: 'true-teacher-dd0a3.firebaseapp.com',
    storageBucket: 'true-teacher-dd0a3.firebasestorage.app',
    measurementId: 'G-Y996XPQSFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LTo6jWE1MNuWb5273xBPD1PQIPeDbd4',
    appId: '1:217250091214:android:2a7b082135e713ff79409f',
    messagingSenderId: '217250091214',
    projectId: 'true-teacher-dd0a3',
    storageBucket: 'true-teacher-dd0a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLSBIz4XnDaJEvQWjd7mtV2fYtp4Tb8E',
    appId: '1:217250091214:ios:10fde1e70a91e76b79409f',
    messagingSenderId: '217250091214',
    projectId: 'true-teacher-dd0a3',
    storageBucket: 'true-teacher-dd0a3.firebasestorage.app',
    iosBundleId: 'trueteacher.120105.com.trueTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLSBIz4XnDaJEvQWjd7mtV2fYtp4Tb8E',
    appId: '1:217250091214:ios:10fde1e70a91e76b79409f',
    messagingSenderId: '217250091214',
    projectId: 'true-teacher-dd0a3',
    storageBucket: 'true-teacher-dd0a3.firebasestorage.app',
    iosBundleId: 'trueteacher.120105.com.trueTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4DXsIIZeRxKIpchmZMMRg9ZnKtxjijDU',
    appId: '1:217250091214:web:5312629fb6a65de279409f',
    messagingSenderId: '217250091214',
    projectId: 'true-teacher-dd0a3',
    authDomain: 'true-teacher-dd0a3.firebaseapp.com',
    storageBucket: 'true-teacher-dd0a3.firebasestorage.app',
    measurementId: 'G-SNL9ZWXFRG',
  );

}